// function handleException(errorMessage: string): never {
//     throw Error(errorMessage);
// }
// handleException('test error');

function runInfinity(): void {
    // while (true) {
    //     console.log('run infinity')
    // }
}
let checkInfinity = runInfinity();
console.log('check a: ', checkInfinity)